resources:
  containers:
  - container: nanoserver
    image: microsoft/nanoserver:1803

jobs:
- job: build_test_harness
  displayName: Build Test Harness
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: Write-Host hello
    displayName: Running a script
- job: other_job
  dependsOn: build_test_harness
  displayName: Run another job
  pool:
    vmImage: ubuntu-16.04
  steps:
    - task: Npm@1
      inputs:
        command: install
        workingDir: projects/npm
- job: containerized_job
  dependsOn: build_test_harness
  displayName: Run a job in a container
  pool:
    vmImage: win1803
  container: nanoserver
  steps:
  - powershell: Write-Host hello
    displayName: Test Running in a container

