jobs:
- job: build_test_harness
  displayName: Build Test Harness
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: Write-Host hello
    displayName: Running a script
- job: other_job
  dependsOn: build_test_harness
  displayName: Run another job
  pool:
    vmImage: ubuntu-16.04
  steps:
  - bash: echo hello
    displayName: Echo hello from linus
- job: containerized_job
  dependsOn: build_test_harness
  displayName: Run a job in a container
  pool:
    vmImage: win1803
  steps:
  - powershell: Write-Host hello
    displayName: Test Running in a container
