resources:
  containers:
  - container: servercore
    image: microsoft/windowsservercore:1803

jobs:
- job: build_test_harness
  displayName: Build Test Harness
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: Write-Host hello
    displayName: Running a script
- job: ubuntu_1604
  dependsOn: build_test_harness
  displayName: Component Detection - Ubuntu 16.04
  pool:
    vmImage: ubuntu-16.04
  steps:
    - task: Npm@1
      inputs:
        command: install
        workingDir: projects/npm
- job: windows_containerized_job
  dependsOn: build_test_harness
  displayName: Component Detection - Windows Container 1803
  pool:
    vmImage: win1803
  container: servercore
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '6.x'
  - task: Npm@1
    inputs:
      command: install
      workingDir: projects/npm
- job: vs2017_win2016_job
  dependsOn: build_test_harness
  displayName: Component Detection - Windows Server 2016
  pool:
    vmImage: vs2017-win2016
  container: servercore
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '6.x'
  - task: Npm@1
    inputs:
      command: install
      workingDir: projects/npm

